server:
  port: 8080

spring:
  datasource:
    url: jdbc:mariadb://10.1.1.1:3306/smartKitchen
    username: agonylua
    password: wei.liu-liu
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

mqtt:
  url: mqtt://10.1.1.1:1883
  clientId: spring-mqtt-client
  username: admin
  password: public
  default-topic: A/B/+,C/B/+

logging:
  level:
    org.springframework.integration: DEBUG  # 文章推荐，用于追踪通道订阅